// users.ts (or employees.ts)

// Auth / basic user
export type Role = "admin" | "employee" | "teamLead";

export type User = {
  id: number;
  name: string;
  email: string;
  password: string;
  role: Role;
};

// Full employee profile
export type Employee = {
  id: number;
  code: string;
  email: string;
  firstName: string;
  middleName?: string;
  lastName: string;
  password: string;
  role: Role;
  department: string;
  location: string;
  shift: "day" | "evening" | "night";

  // Details
  address: string;
  city: string;
  stateRegion: string;
  country: string;
  zip: string;
  phone: string;
  hireDate: string;
  terminationDate?: string;

  // Billing
  workType: "standard" | "overtime";
  billingType: "hourly" | "monthly";
  employeeRate: string;
  employeeCurrency: string;
  billingRateType: "fixed" | "hourly";
  billingCurrency: string;
  billingStart: string;
  billingEnd: string;
};

// Users for login / role checks
export const demoUsers: User[] = [
  {
    id: 1,
    name: "Alex Morgan",
    email: "alex.morgan@timey.ca",
    password: "admin123",
    role: "admin",
  },
  {
    id: 2,
    name: "Emily Thompson",
    email: "emily.thompson@timey.ca",
    password: "admin123",
    role: "admin",
  },
  {
    id: 3,
    name: "Daniel Smith",
    email: "daniel.smith@timey.ca",
    password: "emp123",
    role: "teamLead",
  },
  {
    id: 4,
    name: "Olivia Brown",
    email: "olivia.brown@timey.ca",
    password: "emp123",
    role: "teamLead",
  },
  {
    id: 5,
    name: "Liam Wilson",
    email: "liam.wilson@timey.ca",
    password: "emp123",
    role: "employee",
  },
  {
    id: 6,
    name: "Sophia Martin",
    email: "sophia.martin@timey.ca",
    password: "emp123",
    role: "employee",
  },
  {
    id: 7,
    name: "Ethan Johnson",
    email: "ethan.johnson@timey.ca",
    password: "emp123",
    role: "employee",
  },
  {
    id: 8,
    name: "Ava Clark",
    email: "ava.clark@timey.ca",
    password: "emp123",
    role: "employee",
  },
  {
    id: 9,
    name: "Noah Lee",
    email: "noah.lee@timey.ca",
    password: "emp123",
    role: "employee",
  },
  {
    id: 10,
    name: "Chloe Walker",
    email: "chloe.walker@timey.ca",
    password: "emp123",
    role: "employee",
  },
  {
    id: 11,
    name: "Mason Young",
    email: "mason.young@timey.ca",
    password: "emp123",
    role: "employee",
  },
  {
    id: 12,
    name: "Isabella Scott",
    email: "isabella.scott@timey.ca",
    password: "emp123",
    role: "employee",
  },
  {
    id: 13,
    name: "Logan King",
    email: "logan.king@timey.ca",
    password: "emp123",
    role: "employee",
  },
  {
    id: 14,
    name: "Harper Green",
    email: "harper.green@timey.ca",
    password: "emp123",
    role: "employee",
  },
  {
    id: 15,
    name: "Jacob Harris",
    email: "jacob.harris@timey.ca",
    password: "emp123",
    role: "employee",
  },
  {
    id: 16,
    name: "Abigail Baker",
    email: "abigail.baker@timey.ca",
    password: "emp123",
    role: "employee",
  },
  {
    id: 17,
    name: "Benjamin Cooper",
    email: "benjamin.cooper@timey.ca",
    password: "emp123",
    role: "employee",
  },
  {
    id: 18,
    name: "Ella Parker",
    email: "ella.parker@timey.ca",
    password: "emp123",
    role: "employee",
  },
  {
    id: 19,
    name: "Lucas Turner",
    email: "lucas.turner@timey.ca",
    password: "emp123",
    role: "employee",
  },
  {
    id: 20,
    name: "Grace Mitchell",
    email: "grace.mitchell@timey.ca",
    password: "emp123",
    role: "employee",
  },
  {
    id: 21,
    name: "Nathan Roberts",
    email: "nathan.roberts@timey.ca",
    password: "emp123",
    role: "employee",
  },
];

// Full employee seed data (linked by id)
export const demoEmployees: Employee[] = [
  {
    id: 1,
    code: "EMP-001",
    email: "alex.morgan@timey.ca",
    firstName: "Alex",
    middleName: "",
    lastName: "Morgan",
    password: "admin123",
    role: "admin",
    department: "Management",
    location: "Toronto",
    shift: "day",
    address: "120 King Street West",
    city: "Toronto",
    stateRegion: "Ontario",
    country: "Canada",
    zip: "M5X 1A9",
    phone: "+1-416-555-0101",
    hireDate: "2021-04-10",
    terminationDate: "",
    workType: "standard",
    billingType: "monthly",
    employeeRate: "12000",
    employeeCurrency: "CAD - Canadian Dollar",
    billingRateType: "fixed",
    billingCurrency: "CAD - Canadian Dollar",
    billingStart: "2024-01-01",
    billingEnd: "",
  },
  {
    id: 2,
    code: "EMP-002",
    email: "emily.thompson@timey.ca",
    firstName: "Emily",
    middleName: "",
    lastName: "Thompson",
    password: "admin123",
    role: "admin",
    department: "Operations",
    location: "Vancouver",
    shift: "day",
    address: "808 Burrard Street",
    city: "Vancouver",
    stateRegion: "British Columbia",
    country: "Canada",
    zip: "V6Z 2R9",
    phone: "+1-604-555-0102",
    hireDate: "2022-01-05",
    terminationDate: "",
    workType: "standard",
    billingType: "monthly",
    employeeRate: "11500",
    employeeCurrency: "CAD - Canadian Dollar",
    billingRateType: "fixed",
    billingCurrency: "CAD - Canadian Dollar",
    billingStart: "2024-01-01",
    billingEnd: "",
  },
  {
    id: 3,
    code: "EMP-003",
    email: "daniel.smith@timey.ca",
    firstName: "Daniel",
    middleName: "",
    lastName: "Smith",
    password: "emp123",
    role: "teamLead",
    department: "Engineering",
    location: "Montreal",
    shift: "day",
    address: "2000 Sainte-Catherine Street West",
    city: "Montreal",
    stateRegion: "Quebec",
    country: "Canada",
    zip: "H3H 2T1",
    phone: "+1-514-555-0103",
    hireDate: "2022-06-15",
    terminationDate: "",
    workType: "standard",
    billingType: "monthly",
    employeeRate: "9500",
    employeeCurrency: "CAD - Canadian Dollar",
    billingRateType: "fixed",
    billingCurrency: "CAD - Canadian Dollar",
    billingStart: "2024-04-01",
    billingEnd: "",
  },
  {
    id: 4,
    code: "EMP-004",
    email: "olivia.brown@timey.ca",
    firstName: "Olivia",
    middleName: "",
    lastName: "Brown",
    password: "emp123",
    role: "teamLead",
    department: "Product",
    location: "Calgary",
    shift: "day",
    address: "510 6 Avenue SW",
    city: "Calgary",
    stateRegion: "Alberta",
    country: "Canada",
    zip: "T2P 0S8",
    phone: "+1-403-555-0104",
    hireDate: "2021-11-20",
    terminationDate: "",
    workType: "standard",
    billingType: "monthly",
    employeeRate: "9000",
    employeeCurrency: "CAD - Canadian Dollar",
    billingRateType: "fixed",
    billingCurrency: "CAD - Canadian Dollar",
    billingStart: "2024-01-01",
    billingEnd: "",
  },
  {
    id: 5,
    code: "EMP-005",
    email: "liam.wilson@timey.ca",
    firstName: "Liam",
    middleName: "",
    lastName: "Wilson",
    password: "emp123",
    role: "employee",
    department: "Engineering",
    location: "Ottawa",
    shift: "day",
    address: "90 Elgin Street",
    city: "Ottawa",
    stateRegion: "Ontario",
    country: "Canada",
    zip: "K1P 5K8",
    phone: "+1-613-555-0105",
    hireDate: "2023-02-10",
    terminationDate: "",
    workType: "standard",
    billingType: "hourly",
    employeeRate: "55",
    employeeCurrency: "CAD - Canadian Dollar",
    billingRateType: "hourly",
    billingCurrency: "CAD - Canadian Dollar",
    billingStart: "2024-05-01",
    billingEnd: "",
  },
  {
    id: 6,
    code: "EMP-006",
    email: "sophia.martin@timey.ca",
    firstName: "Sophia",
    middleName: "",
    lastName: "Martin",
    password: "emp123",
    role: "employee",
    department: "Engineering",
    location: "Toronto",
    shift: "evening",
    address: "350 Queen Street West",
    city: "Toronto",
    stateRegion: "Ontario",
    country: "Canada",
    zip: "M5V 2A2",
    phone: "+1-416-555-0106",
    hireDate: "2022-09-01",
    terminationDate: "",
    workType: "overtime",
    billingType: "hourly",
    employeeRate: "60",
    employeeCurrency: "CAD - Canadian Dollar",
    billingRateType: "hourly",
    billingCurrency: "CAD - Canadian Dollar",
    billingStart: "2024-03-01",
    billingEnd: "",
  },
  {
    id: 7,
    code: "EMP-007",
    email: "ethan.johnson@timey.ca",
    firstName: "Ethan",
    middleName: "",
    lastName: "Johnson",
    password: "emp123",
    role: "employee",
    department: "Design",
    location: "Vancouver",
    shift: "day",
    address: "700 Granville Street",
    city: "Vancouver",
    stateRegion: "British Columbia",
    country: "Canada",
    zip: "V7Y 1K8",
    phone: "+1-604-555-0107",
    hireDate: "2023-04-05",
    terminationDate: "",
    workType: "standard",
    billingType: "monthly",
    employeeRate: "7000",
    employeeCurrency: "CAD - Canadian Dollar",
    billingRateType: "fixed",
    billingCurrency: "CAD - Canadian Dollar",
    billingStart: "2024-02-01",
    billingEnd: "",
  },
  {
    id: 8,
    code: "EMP-008",
    email: "ava.clark@timey.ca",
    firstName: "Ava",
    middleName: "",
    lastName: "Clark",
    password: "emp123",
    role: "employee",
    department: "QA",
    location: "Edmonton",
    shift: "night",
    address: "10025 Jasper Avenue",
    city: "Edmonton",
    stateRegion: "Alberta",
    country: "Canada",
    zip: "T5J 1S5",
    phone: "+1-780-555-0108",
    hireDate: "2021-08-18",
    terminationDate: "",
    workType: "overtime",
    billingType: "hourly",
    employeeRate: "48",
    employeeCurrency: "CAD - Canadian Dollar",
    billingRateType: "hourly",
    billingCurrency: "CAD - Canadian Dollar",
    billingStart: "2024-06-01",
    billingEnd: "",
  },
  {
    id: 9,
    code: "EMP-009",
    email: "noah.lee@timey.ca",
    firstName: "Noah",
    middleName: "",
    lastName: "Lee",
    password: "emp123",
    role: "employee",
    department: "HR",
    location: "Winnipeg",
    shift: "day",
    address: "201 Portage Avenue",
    city: "Winnipeg",
    stateRegion: "Manitoba",
    country: "Canada",
    zip: "R3B 3K6",
    phone: "+1-204-555-0109",
    hireDate: "2020-12-10",
    terminationDate: "",
    workType: "standard",
    billingType: "monthly",
    employeeRate: "5200",
    employeeCurrency: "CAD - Canadian Dollar",
    billingRateType: "fixed",
    billingCurrency: "CAD - Canadian Dollar",
    billingStart: "2024-01-01",
    billingEnd: "",
  },
  {
    id: 10,
    code: "EMP-010",
    email: "chloe.walker@timey.ca",
    firstName: "Chloe",
    middleName: "",
    lastName: "Walker",
    password: "emp123",
    role: "employee",
    department: "Support",
    location: "Halifax",
    shift: "night",
    address: "1801 Hollis Street",
    city: "Halifax",
    stateRegion: "Nova Scotia",
    country: "Canada",
    zip: "B3J 3N4",
    phone: "+1-902-555-0110",
    hireDate: "2022-01-22",
    terminationDate: "",
    workType: "standard",
    billingType: "hourly",
    employeeRate: "42",
    employeeCurrency: "CAD - Canadian Dollar",
    billingRateType: "hourly",
    billingCurrency: "CAD - Canadian Dollar",
    billingStart: "2024-04-01",
    billingEnd: "",
  },
  {
    id: 11,
    code: "EMP-011",
    email: "mason.young@timey.ca",
    firstName: "Mason",
    middleName: "",
    lastName: "Young",
    password: "emp123",
    role: "employee",
    department: "Operations",
    location: "Quebec City",
    shift: "day",
    address: "1000 Boulevard René-Lévesque E",
    city: "Quebec City",
    stateRegion: "Quebec",
    country: "Canada",
    zip: "G1R 5T8",
    phone: "+1-418-555-0111",
    hireDate: "2023-07-01",
    terminationDate: "",
    workType: "standard",
    billingType: "monthly",
    employeeRate: "4800",
    employeeCurrency: "CAD - Canadian Dollar",
    billingRateType: "fixed",
    billingCurrency: "CAD - Canadian Dollar",
    billingStart: "2024-07-01",
    billingEnd: "",
  },
  {
    id: 12,
    code: "EMP-012",
    email: "isabella.scott@timey.ca",
    firstName: "Isabella",
    middleName: "",
    lastName: "Scott",
    password: "emp123",
    role: "employee",
    department: "Engineering",
    location: "Hamilton",
    shift: "evening",
    address: "1 James Street South",
    city: "Hamilton",
    stateRegion: "Ontario",
    country: "Canada",
    zip: "L8P 4R5",
    phone: "+1-905-555-0112",
    hireDate: "2021-05-30",
    terminationDate: "",
    workType: "overtime",
    billingType: "hourly",
    employeeRate: "58",
    employeeCurrency: "CAD - Canadian Dollar",
    billingRateType: "hourly",
    billingCurrency: "CAD - Canadian Dollar",
    billingStart: "2024-03-15",
    billingEnd: "",
  },
  {
    id: 13,
    code: "EMP-013",
    email: "logan.king@timey.ca",
    firstName: "Logan",
    middleName: "",
    lastName: "King",
    password: "emp123",
    role: "employee",
    department: "Marketing",
    location: "Mississauga",
    shift: "day",
    address: "100 City Centre Drive",
    city: "Mississauga",
    stateRegion: "Ontario",
    country: "Canada",
    zip: "L5B 2C9",
    phone: "+1-905-555-0113",
    hireDate: "2022-02-14",
    terminationDate: "",
    workType: "standard",
    billingType: "monthly",
    employeeRate: "6000",
    employeeCurrency: "CAD - Canadian Dollar",
    billingRateType: "fixed",
    billingCurrency: "CAD - Canadian Dollar",
    billingStart: "2024-01-10",
    billingEnd: "",
  },
  {
    id: 14,
    code: "EMP-014",
    email: "harper.green@timey.ca",
    firstName: "Harper",
    middleName: "",
    lastName: "Green",
    password: "emp123",
    role: "employee",
    department: "Finance",
    location: "Regina",
    shift: "day",
    address: "2101 Saskatchewan Drive",
    city: "Regina",
    stateRegion: "Saskatchewan",
    country: "Canada",
    zip: "S4P 4G9",
    phone: "+1-306-555-0114",
    hireDate: "2020-09-03",
    terminationDate: "",
    workType: "standard",
    billingType: "monthly",
    employeeRate: "6300",
    employeeCurrency: "CAD - Canadian Dollar",
    billingRateType: "fixed",
    billingCurrency: "CAD - Canadian Dollar",
    billingStart: "2024-02-01",
    billingEnd: "",
  },
  {
    id: 15,
    code: "EMP-015",
    email: "jacob.harris@timey.ca",
    firstName: "Jacob",
    middleName: "",
    lastName: "Harris",
    password: "emp123",
    role: "employee",
    department: "Engineering",
    location: "Saskatoon",
    shift: "day",
    address: "101 21st Street East",
    city: "Saskatoon",
    stateRegion: "Saskatchewan",
    country: "Canada",
    zip: "S7K 0C1",
    phone: "+1-306-555-0115",
    hireDate: "2023-01-12",
    terminationDate: "",
    workType: "standard",
    billingType: "hourly",
    employeeRate: "52",
    employeeCurrency: "CAD - Canadian Dollar",
    billingRateType: "hourly",
    billingCurrency: "CAD - Canadian Dollar",
    billingStart: "2024-05-15",
    billingEnd: "",
  },
  {
    id: 16,
    code: "EMP-016",
    email: "abigail.baker@timey.ca",
    firstName: "Abigail",
    middleName: "",
    lastName: "Baker",
    password: "emp123",
    role: "employee",
    department: "Support",
    location: "St. John’s",
    shift: "night",
    address: "215 Water Street",
    city: "St. John’s",
    stateRegion: "Newfoundland and Labrador",
    country: "Canada",
    zip: "A1C 1A9",
    phone: "+1-709-555-0116",
    hireDate: "2021-10-19",
    terminationDate: "",
    workType: "overtime",
    billingType: "hourly",
    employeeRate: "45",
    employeeCurrency: "CAD - Canadian Dollar",
    billingRateType: "hourly",
    billingCurrency: "CAD - Canadian Dollar",
    billingStart: "2024-06-01",
    billingEnd: "",
  },
  {
    id: 17,
    code: "EMP-017",
    email: "benjamin.cooper@timey.ca",
    firstName: "Benjamin",
    middleName: "",
    lastName: "Cooper",
    password: "emp123",
    role: "employee",
    department: "Customer Success",
    location: "Victoria",
    shift: "day",
    address: "525 Fort Street",
    city: "Victoria",
    stateRegion: "British Columbia",
    country: "Canada",
    zip: "V8W 1E7",
    phone: "+1-250-555-0117",
    hireDate: "2022-03-08",
    terminationDate: "",
    workType: "standard",
    billingType: "monthly",
    employeeRate: "5600",
    employeeCurrency: "CAD - Canadian Dollar",
    billingRateType: "fixed",
    billingCurrency: "CAD - Canadian Dollar",
    billingStart: "2024-03-01",
    billingEnd: "",
  },
  {
    id: 18,
    code: "EMP-018",
    email: "ella.parker@timey.ca",
    firstName: "Ella",
    middleName: "",
    lastName: "Parker",
    password: "emp123",
    role: "employee",
    department: "Engineering",
    location: "Kelowna",
    shift: "evening",
    address: "275 Bernard Avenue",
    city: "Kelowna",
    stateRegion: "British Columbia",
    country: "Canada",
    zip: "V1Y 6N2",
    phone: "+1-250-555-0118",
    hireDate: "2021-07-11",
    terminationDate: "",
    workType: "overtime",
    billingType: "hourly",
    employeeRate: "57",
    employeeCurrency: "CAD - Canadian Dollar",
    billingRateType: "hourly",
    billingCurrency: "CAD - Canadian Dollar",
    billingStart: "2024-04-10",
    billingEnd: "",
  },
  {
    id: 19,
    code: "EMP-019",
    email: "lucas.turner@timey.ca",
    firstName: "Lucas",
    middleName: "",
    lastName: "Turner",
    password: "emp123",
    role: "employee",
    department: "Design",
    location: "Moncton",
    shift: "day",
    address: "770 Main Street",
    city: "Moncton",
    stateRegion: "New Brunswick",
    country: "Canada",
    zip: "E1C 1E7",
    phone: "+1-506-555-0119",
    hireDate: "2023-05-21",
    terminationDate: "",
    workType: "standard",
    billingType: "monthly",
    employeeRate: "5900",
    employeeCurrency: "CAD - Canadian Dollar",
    billingRateType: "fixed",
    billingCurrency: "CAD - Canadian Dollar",
    billingStart: "2024-05-01",
    billingEnd: "",
  },
  {
    id: 20,
    code: "EMP-020",
    email: "grace.mitchell@timey.ca",
    firstName: "Grace",
    middleName: "",
    lastName: "Mitchell",
    password: "emp123",
    role: "employee",
    department: "Engineering",
    location: "Charlottetown",
    shift: "day",
    address: "94 Queen Street",
    city: "Charlottetown",
    stateRegion: "Prince Edward Island",
    country: "Canada",
    zip: "C1A 4A9",
    phone: "+1-902-555-0120",
    hireDate: "2022-08-02",
    terminationDate: "",
    workType: "standard",
    billingType: "hourly",
    employeeRate: "50",
    employeeCurrency: "CAD - Canadian Dollar",
    billingRateType: "hourly",
    billingCurrency: "CAD - Canadian Dollar",
    billingStart: "2024-06-15",
    billingEnd: "",
  },
  {
    id: 21,
    code: "EMP-021",
    email: "nathan.roberts@timey.ca",
    firstName: "Nathan",
    middleName: "",
    lastName: "Roberts",
    password: "emp123",
    role: "employee",
    department: "Analytics",
    location: "Whitehorse",
    shift: "day",
    address: "212 Main Street",
    city: "Whitehorse",
    stateRegion: "Yukon",
    country: "Canada",
    zip: "Y1A 2A7",
    phone: "+1-867-555-0121",
    hireDate: "2023-09-05",
    terminationDate: "",
    workType: "standard",
    billingType: "monthly",
    employeeRate: "6100",
    employeeCurrency: "CAD - Canadian Dollar",
    billingRateType: "fixed",
    billingCurrency: "CAD - Canadian Dollar",
    billingStart: "2024-07-01",
    billingEnd: "",
  },
];
