// users.ts (or employees.ts)

// Auth / basic user
export type Role = "admin" | "employee" | "teamLead";

export type User = {
  id: number;
  name: string;
  email: string;
  password: string;
  role: Role;
};

// Full employee profile (matches your useState fields)
export type Employee = {
  id: number;
  code: string;
  email: string;
  firstName: string;
  middleName?: string;
  lastName: string;
  password: string;
  role: Role;
  department: string;
  location: string;
  shift: "day" | "evening" | "night";

  // Details
  address: string;
  city: string;
  stateRegion: string;
  country: string;
  zip: string;
  phone: string;
  hireDate: string;        // ISO date string
  terminationDate?: string;

  // Billing
  workType: "standard" | "overtime";
  billingType: "hourly" | "monthly";
  employeeRate: string;
  employeeCurrency: string;
  billingRateType: "fixed" | "hourly";
  billingCurrency: string;
  billingStart: string;
  billingEnd: string;
};

// Users for login / role checks
export const demoUsers: User[] = [
  {
    id: 1,
    name: "Rohit Mehra",
    email: "rohit.mehra@timey.com",
    password: "admin123",
    role: "admin",
  },
  {
    id: 2,
    name: "Ananya Kapoor",
    email: "ananya.kapoor@timey.com",
    password: "admin123",
    role: "admin",
  },
  {
    id: 3,
    name: "Priya Sharma",
    email: "priya.sharma@timey.com",
    password: "emp123",
    role: "teamLead",
  },
  {
    id: 4,
    name: "Aman Verma",
    email: "aman.verma@timey.com",
    password: "emp123",
    role: "teamLead",
  },
  {
    id: 5,
    name: "Neha Patel",
    email: "neha.patel@timey.com",
    password: "emp123",
    role: "employee",
  },
  {
    id: 6,
    name: "Arjun Singh",
    email: "arjun.singh@timey.com",
    password: "emp123",
    role: "employee",
  },
  {
    id: 7,
    name: "Simran Kaur",
    email: "simran.kaur@timey.com",
    password: "emp123",
    role: "employee",
  },
  {
    id: 8,
    name: "Karan Desai",
    email: "karan.desai@timey.com",
    password: "emp123",
    role: "employee",
  },
  {
    id: 9,
    name: "Anjali Gupta",
    email: "anjali.gupta@timey.com",
    password: "emp123",
    role: "employee",
  },
  {
    id: 10,
    name: "Vikram Rao",
    email: "vikram.rao@timey.com",
    password: "emp123",
    role: "employee",
  },
  {
    id: 11,
    name: "Muskan Jain",
    email: "muskan.jain@timey.com",
    password: "emp123",
    role: "employee",
  },
  {
    id: 12,
    name: "Farhan Ali",
    email: "farhan.ali@timey.com",
    password: "emp123",
    role: "employee",
  },
  {
    id: 13,
    name: "Isha Reddy",
    email: "isha.reddy@timey.com",
    password: "emp123",
    role: "employee",
  },
  {
    id: 14,
    name: "Deepak Kumar",
    email: "deepak.kumar@timey.com",
    password: "emp123",
    role: "employee",
  },
  {
    id: 15,
    name: "Ritika Joshi",
    email: "ritika.joshi@timey.com",
    password: "emp123",
    role: "employee",
  },
  {
    id: 16,
    name: "Saurabh Mishra",
    email: "saurabh.mishra@timey.com",
    password: "emp123",
    role: "employee",
  },
  {
    id: 17,
    name: "Pooja Nair",
    email: "pooja.nair@timey.com",
    password: "emp123",
    role: "employee",
  },
  {
    id: 18,
    name: "Rahul Chatterjee",
    email: "rahul.chatterjee@timey.com",
    password: "emp123",
    role: "employee",
  },
  {
    id: 19,
    name: "Sneha Iyer",
    email: "sneha.iyer@timey.com",
    password: "emp123",
    role: "employee",
  },
  {
    id: 20,
    name: "Aditya Malhotra",
    email: "aditya.malhotra@timey.com",
    password: "emp123",
    role: "employee",
  },
  {
    id: 21,
    name: "Kavya Saxena",
    email: "kavya.saxena@timey.com",
    password: "emp123",
    role: "employee",
  },
];

// Full employee seed data (linked by id)
export const demoEmployees: Employee[] = [
  {
    id: 1,
    code: "EMP-001",
    email: "rohit.mehra@timey.com",
    firstName: "Rohit",
    middleName: "",
    lastName: "Mehra",
    password: "admin123",
    role: "admin",
    department: "Management",
    location: "Gurugram",
    shift: "day",
    address: "12 Golf Course Road",
    city: "Gurugram",
    stateRegion: "Haryana",
    country: "India",
    zip: "122002",
    phone: "+91-9876543200",
    hireDate: "2021-04-10",
    terminationDate: "",
    workType: "standard",
    billingType: "monthly",
    employeeRate: "120000",
    employeeCurrency: "INR - Indian Rupee",
    billingRateType: "fixed",
    billingCurrency: "INR - Indian Rupee",
    billingStart: "2024-01-01",
    billingEnd: "",
  },
  {
    id: 2,
    code: "EMP-002",
    email: "ananya.kapoor@timey.com",
    firstName: "Ananya",
    middleName: "",
    lastName: "Kapoor",
    password: "admin123",
    role: "admin",
    department: "Operations",
    location: "Bengaluru",
    shift: "day",
    address: "8 Residency Road",
    city: "Bengaluru",
    stateRegion: "Karnataka",
    country: "India",
    zip: "560025",
    phone: "+91-9845012345",
    hireDate: "2022-01-05",
    terminationDate: "",
    workType: "standard",
    billingType: "monthly",
    employeeRate: "110000",
    employeeCurrency: "INR - Indian Rupee",
    billingRateType: "fixed",
    billingCurrency: "INR - Indian Rupee",
    billingStart: "2024-01-01",
    billingEnd: "",
  },
  {
    id: 3,
    code: "EMP-003",
    email: "priya.sharma@timey.com",
    firstName: "Priya",
    middleName: "",
    lastName: "Sharma",
    password: "emp123",
    role: "teamLead",
    department: "Engineering",
    location: "Noida",
    shift: "day",
    address: "21 Sector 62",
    city: "Noida",
    stateRegion: "Uttar Pradesh",
    country: "India",
    zip: "201301",
    phone: "+91-9899001122",
    hireDate: "2022-06-15",
    terminationDate: "",
    workType: "standard",
    billingType: "monthly",
    employeeRate: "95000",
    employeeCurrency: "INR - Indian Rupee",
    billingRateType: "fixed",
    billingCurrency: "INR - Indian Rupee",
    billingStart: "2024-04-01",
    billingEnd: "",
  },
  {
    id: 4,
    code: "EMP-004",
    email: "aman.verma@timey.com",
    firstName: "Aman",
    middleName: "",
    lastName: "Verma",
    password: "emp123",
    role: "teamLead",
    department: "Product",
    location: "Mumbai",
    shift: "day",
    address: "502 Andheri East",
    city: "Mumbai",
    stateRegion: "Maharashtra",
    country: "India",
    zip: "400069",
    phone: "+91-9820112233",
    hireDate: "2021-11-20",
    terminationDate: "",
    workType: "standard",
    billingType: "monthly",
    employeeRate: "88000",
    employeeCurrency: "INR - Indian Rupee",
    billingRateType: "fixed",
    billingCurrency: "INR - Indian Rupee",
    billingStart: "2024-01-01",
    billingEnd: "",
  },
  {
    id: 5,
    code: "EMP-005",
    email: "neha.patel@timey.com",
    firstName: "Neha",
    middleName: "",
    lastName: "Patel",
    password: "emp123",
    role: "employee",
    department: "Engineering",
    location: "Ahmedabad",
    shift: "day",
    address: "14 Satellite Road",
    city: "Ahmedabad",
    stateRegion: "Gujarat",
    country: "India",
    zip: "380015",
    phone: "+91-9879005566",
    hireDate: "2023-02-10",
    terminationDate: "",
    workType: "standard",
    billingType: "hourly",
    employeeRate: "850",
    employeeCurrency: "INR - Indian Rupee",
    billingRateType: "hourly",
    billingCurrency: "INR - Indian Rupee",
    billingStart: "2024-05-01",
    billingEnd: "",
  },
  {
    id: 6,
    code: "EMP-006",
    email: "arjun.singh@timey.com",
    firstName: "Arjun",
    middleName: "",
    lastName: "Singh",
    password: "emp123",
    role: "employee",
    department: "Engineering",
    location: "Noida",
    shift: "evening",
    address: "C-45 Sector 15",
    city: "Noida",
    stateRegion: "Uttar Pradesh",
    country: "India",
    zip: "201301",
    phone: "+91-9810012345",
    hireDate: "2022-09-01",
    terminationDate: "",
    workType: "overtime",
    billingType: "hourly",
    employeeRate: "900",
    employeeCurrency: "INR - Indian Rupee",
    billingRateType: "hourly",
    billingCurrency: "INR - Indian Rupee",
    billingStart: "2024-03-01",
    billingEnd: "",
  },
  {
    id: 7,
    code: "EMP-007",
    email: "simran.kaur@timey.com",
    firstName: "Simran",
    middleName: "",
    lastName: "Kaur",
    password: "emp123",
    role: "employee",
    department: "Design",
    location: "Mumbai",
    shift: "day",
    address: "304 Bandra West",
    city: "Mumbai",
    stateRegion: "Maharashtra",
    country: "India",
    zip: "400050",
    phone: "+91-9819123456",
    hireDate: "2023-04-05",
    terminationDate: "",
    workType: "standard",
    billingType: "monthly",
    employeeRate: "65000",
    employeeCurrency: "INR - Indian Rupee",
    billingRateType: "fixed",
    billingCurrency: "INR - Indian Rupee",
    billingStart: "2024-02-01",
    billingEnd: "",
  },
  {
    id: 8,
    code: "EMP-008",
    email: "karan.desai@timey.com",
    firstName: "Karan",
    middleName: "",
    lastName: "Desai",
    password: "emp123",
    role: "employee",
    department: "QA",
    location: "Pune",
    shift: "night",
    address: "19 Kothrud",
    city: "Pune",
    stateRegion: "Maharashtra",
    country: "India",
    zip: "411038",
    phone: "+91-9822007788",
    hireDate: "2021-08-18",
    terminationDate: "",
    workType: "overtime",
    billingType: "hourly",
    employeeRate: "780",
    employeeCurrency: "INR - Indian Rupee",
    billingRateType: "hourly",
    billingCurrency: "INR - Indian Rupee",
    billingStart: "2024-06-01",
    billingEnd: "",
  },
  {
    id: 9,
    code: "EMP-009",
    email: "anjali.gupta@timey.com",
    firstName: "Anjali",
    middleName: "",
    lastName: "Gupta",
    password: "emp123",
    role: "employee",
    department: "HR",
    location: "Delhi",
    shift: "day",
    address: "B-12 Lajpat Nagar",
    city: "New Delhi",
    stateRegion: "Delhi",
    country: "India",
    zip: "110024",
    phone: "+91-9899112233",
    hireDate: "2020-12-10",
    terminationDate: "",
    workType: "standard",
    billingType: "monthly",
    employeeRate: "52000",
    employeeCurrency: "INR - Indian Rupee",
    billingRateType: "fixed",
    billingCurrency: "INR - Indian Rupee",
    billingStart: "2024-01-01",
    billingEnd: "",
  },
  {
    id: 10,
    code: "EMP-010",
    email: "vikram.rao@timey.com",
    firstName: "Vikram",
    middleName: "",
    lastName: "Rao",
    password: "emp123",
    role: "employee",
    department: "Support",
    location: "Hyderabad",
    shift: "night",
    address: "7 Kukatpally",
    city: "Hyderabad",
    stateRegion: "Telangana",
    country: "India",
    zip: "500072",
    phone: "+91-9000556677",
    hireDate: "2022-01-22",
    terminationDate: "",
    workType: "standard",
    billingType: "hourly",
    employeeRate: "600",
    employeeCurrency: "INR - Indian Rupee",
    billingRateType: "hourly",
    billingCurrency: "INR - Indian Rupee",
    billingStart: "2024-04-01",
    billingEnd: "",
  },
  {
    id: 11,
    code: "EMP-011",
    email: "muskan.jain@timey.com",
    firstName: "Muskan",
    middleName: "",
    lastName: "Jain",
    password: "emp123",
    role: "employee",
    department: "Operations",
    location: "Jaipur",
    shift: "day",
    address: "23 Vaishali Nagar",
    city: "Jaipur",
    stateRegion: "Rajasthan",
    country: "India",
    zip: "302021",
    phone: "+91-9829123456",
    hireDate: "2023-07-01",
    terminationDate: "",
    workType: "standard",
    billingType: "monthly",
    employeeRate: "48000",
    employeeCurrency: "INR - Indian Rupee",
    billingRateType: "fixed",
    billingCurrency: "INR - Indian Rupee",
    billingStart: "2024-07-01",
    billingEnd: "",
  },
  {
    id: 12,
    code: "EMP-012",
    email: "farhan.ali@timey.com",
    firstName: "Farhan",
    middleName: "",
    lastName: "Ali",
    password: "emp123",
    role: "employee",
    department: "Engineering",
    location: "Chennai",
    shift: "evening",
    address: "16 T Nagar",
    city: "Chennai",
    stateRegion: "Tamil Nadu",
    country: "India",
    zip: "600017",
    phone: "+91-9940011223",
    hireDate: "2021-05-30",
    terminationDate: "",
    workType: "overtime",
    billingType: "hourly",
    employeeRate: "920",
    employeeCurrency: "INR - Indian Rupee",
    billingRateType: "hourly",
    billingCurrency: "INR - Indian Rupee",
    billingStart: "2024-03-15",
    billingEnd: "",
  },
  {
    id: 13,
    code: "EMP-013",
    email: "isha.reddy@timey.com",
    firstName: "Isha",
    middleName: "",
    lastName: "Reddy",
    password: "emp123",
    role: "employee",
    department: "Marketing",
    location: "Bengaluru",
    shift: "day",
    address: "55 Indiranagar",
    city: "Bengaluru",
    stateRegion: "Karnataka",
    country: "India",
    zip: "560038",
    phone: "+91-9986012345",
    hireDate: "2022-02-14",
    terminationDate: "",
    workType: "standard",
    billingType: "monthly",
    employeeRate: "57000",
    employeeCurrency: "INR - Indian Rupee",
    billingRateType: "fixed",
    billingCurrency: "INR - Indian Rupee",
    billingStart: "2024-01-10",
    billingEnd: "",
  },
  {
    id: 14,
    code: "EMP-014",
    email: "deepak.kumar@timey.com",
    firstName: "Deepak",
    middleName: "",
    lastName: "Kumar",
    password: "emp123",
    role: "employee",
    department: "Finance",
    location: "Kolkata",
    shift: "day",
    address: "3 Salt Lake Sector V",
    city: "Kolkata",
    stateRegion: "West Bengal",
    country: "India",
    zip: "700091",
    phone: "+91-9830011223",
    hireDate: "2020-09-03",
    terminationDate: "",
    workType: "standard",
    billingType: "monthly",
    employeeRate: "63000",
    employeeCurrency: "INR - Indian Rupee",
    billingRateType: "fixed",
    billingCurrency: "INR - Indian Rupee",
    billingStart: "2024-02-01",
    billingEnd: "",
  },
  {
    id: 15,
    code: "EMP-015",
    email: "ritika.joshi@timey.com",
    firstName: "Ritika",
    middleName: "",
    lastName: "Joshi",
    password: "emp123",
    role: "employee",
    department: "Engineering",
    location: "Surat",
    shift: "day",
    address: "10 Varachha Road",
    city: "Surat",
    stateRegion: "Gujarat",
    country: "India",
    zip: "395006",
    phone: "+91-9876543219",
    hireDate: "2023-01-12",
    terminationDate: "",
    workType: "standard",
    billingType: "hourly",
    employeeRate: "800",
    employeeCurrency: "INR - Indian Rupee",
    billingRateType: "hourly",
    billingCurrency: "INR - Indian Rupee",
    billingStart: "2024-05-15",
    billingEnd: "",
  },
  {
    id: 16,
    code: "EMP-016",
    email: "saurabh.mishra@timey.com",
    firstName: "Saurabh",
    middleName: "",
    lastName: "Mishra",
    password: "emp123",
    role: "employee",
    department: "Support",
    location: "Lucknow",
    shift: "night",
    address: "27 Gomti Nagar",
    city: "Lucknow",
    stateRegion: "Uttar Pradesh",
    country: "India",
    zip: "226010",
    phone: "+91-9795332211",
    hireDate: "2021-10-19",
    terminationDate: "",
    workType: "overtime",
    billingType: "hourly",
    employeeRate: "610",
    employeeCurrency: "INR - Indian Rupee",
    billingRateType: "hourly",
    billingCurrency: "INR - Indian Rupee",
    billingStart: "2024-06-01",
    billingEnd: "",
  },
  {
    id: 17,
    code: "EMP-017",
    email: "pooja.nair@timey.com",
    firstName: "Pooja",
    middleName: "",
    lastName: "Nair",
    password: "emp123",
    role: "employee",
    department: "Customer Success",
    location: "Kochi",
    shift: "day",
    address: "44 Marine Drive",
    city: "Kochi",
    stateRegion: "Kerala",
    country: "India",
    zip: "682031",
    phone: "+91-9847012345",
    hireDate: "2022-03-08",
    terminationDate: "",
    workType: "standard",
    billingType: "monthly",
    employeeRate: "54000",
    employeeCurrency: "INR - Indian Rupee",
    billingRateType: "fixed",
    billingCurrency: "INR - Indian Rupee",
    billingStart: "2024-03-01",
    billingEnd: "",
  },
  {
    id: 18,
    code: "EMP-018",
    email: "rahul.chatterjee@timey.com",
    firstName: "Rahul",
    middleName: "",
    lastName: "Chatterjee",
    password: "emp123",
    role: "employee",
    department: "Engineering",
    location: "Indore",
    shift: "evening",
    address: "9 Vijay Nagar",
    city: "Indore",
    stateRegion: "Madhya Pradesh",
    country: "India",
    zip: "452010",
    phone: "+91-9755012345",
    hireDate: "2021-07-11",
    terminationDate: "",
    workType: "overtime",
    billingType: "hourly",
    employeeRate: "870",
    employeeCurrency: "INR - Indian Rupee",
    billingRateType: "hourly",
    billingCurrency: "INR - Indian Rupee",
    billingStart: "2024-04-10",
    billingEnd: "",
  },
  {
    id: 19,
    code: "EMP-019",
    email: "sneha.iyer@timey.com",
    firstName: "Sneha",
    middleName: "",
    lastName: "Iyer",
    password: "emp123",
    role: "employee",
    department: "Design",
    location: "Chandigarh",
    shift: "day",
    address: "11 Sector 22",
    city: "Chandigarh",
    stateRegion: "Chandigarh",
    country: "India",
    zip: "160022",
    phone: "+91-9803012345",
    hireDate: "2023-05-21",
    terminationDate: "",
    workType: "standard",
    billingType: "monthly",
    employeeRate: "61000",
    employeeCurrency: "INR - Indian Rupee",
    billingRateType: "fixed",
    billingCurrency: "INR - Indian Rupee",
    billingStart: "2024-05-01",
    billingEnd: "",
  },
  {
    id: 20,
    code: "EMP-020",
    email: "aditya.malhotra@timey.com",
    firstName: "Aditya",
    middleName: "",
    lastName: "Malhotra",
    password: "emp123",
    role: "employee",
    department: "Engineering",
    location: "Nagpur",
    shift: "day",
    address: "6 Dharampeth",
    city: "Nagpur",
    stateRegion: "Maharashtra",
    country: "India",
    zip: "440010",
    phone: "+91-9730012345",
    hireDate: "2022-08-02",
    terminationDate: "",
    workType: "standard",
    billingType: "hourly",
    employeeRate: "830",
    employeeCurrency: "INR - Indian Rupee",
    billingRateType: "hourly",
    billingCurrency: "INR - Indian Rupee",
    billingStart: "2024-06-15",
    billingEnd: "",
  },
  {
    id: 21,
    code: "EMP-021",
    email: "kavya.saxena@timey.com",
    firstName: "Kavya",
    middleName: "",
    lastName: "Saxena",
    password: "emp123",
    role: "employee",
    department: "Analytics",
    location: "Patna",
    shift: "day",
    address: "32 Boring Road",
    city: "Patna",
    stateRegion: "Bihar",
    country: "India",
    zip: "800001",
    phone: "+91-9771012345",
    hireDate: "2023-09-05",
    terminationDate: "",
    workType: "standard",
    billingType: "monthly",
    employeeRate: "59000",
    employeeCurrency: "INR - Indian Rupee",
    billingRateType: "fixed",
    billingCurrency: "INR - Indian Rupee",
    billingStart: "2024-07-01",
    billingEnd: "",
  },
];
